doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            EventType: App\Domain\Event\EventType

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Event:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Infrastructure/ORM/Event/Mapping'
                prefix: 'App\Domain\Event'
                alias: Event
            Repo:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Infrastructure/ORM/Repo/Mapping'
                prefix: 'App\Domain\Repo'
                alias: Repo
            Actor:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Infrastructure/ORM/Actor/Mapping'
                prefix: 'App\Domain\Actor'
                alias: Actor

when@test:
    doctrine:
        dbal:
            dbname_suffix: '_test'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
